# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Kenneth's simple site"
title_separator          : "-"
name                     : "Kenneth Beck."
description              : "The greatest quick website"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://github.com/RMgametopspot/ReadME/blob/main/README.md # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "https://github.com/RMgametopspot/ReadME/blob/main/Resume.pdf"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUTEhAVFRUSFRUVFRUXFRUVFRUVFRUXFhUVFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGxAQGy0lHSUtLS0tLS0tLS0tLS0tLS0tLS0tKy0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLSstLS0tLf/AABEIAOoA2AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAADAQIEBQYABwj/xAA+EAABAwIDBQYDBQgCAgMAAAABAAIDBBESITEFBkFRYRMicYGRsQcyoRRScoLBFSMzQmKS0eGy8IPxNFOT/8QAGQEAAwEBAQAAAAAAAAAAAAAAAAIEAwEF/8QAIxEAAwACAgMAAwEBAQAAAAAAAAECAxEhMQQSQRMiUTKBI//aAAwDAQACEQMRAD8A9fiJadFMLbhBRI32QAMwrhknSVAHXwTBUg6ttdABgUhKbiSEoAUOXELguLkAcCucUl026AHArnyAAkkADMkmwA5knRZ/e3euGgjDn96R9+ziBsXW4k/ytHP0uvFNvb11Na8mWTujMRtu2Nvg3iepueqyvKp4+muPE65+HsW1fiHQQ5CUyuHCIYh/eSGnyJWcq/i4R/Corjm+W30a0+68pa8nPgjPkFtSD9VO8uRlSw40b6p+K1cQcEFOy/E43EeWIeyr2fFjaDTdwp3DiDG4ehDwsX2ruJ8tSodW9vNL73/Rvxx/D2fYPxhppO7UwvhcP5mXljP0Dh4WPit5sjbdNVNxU87JAMyAe8PxMPeb5hfKbG530U+jrHxua+N7mOacnNJa4HoRmFp+drsyeCX1wfVbgkYbLy7cz4mEgR13gJwLf/q0ZfmHmOK9QaQQCCCCLgjMEHQgqmaVLaJbhy9MI5cCmhcUwoRdZDulxIAeUwlI96YXIAfdchgrkAMc6yE+S+WdkVsLeK4xAaIAZTYTlxHHijSRAhQqg4SHcsj4KW11wCDqgDoxwKdZKFwKAHBI5KuQAxRNsbRZTQSTy/JE0uNtTbRo6k2A6kKaV5v8bNoEU8NODbtpMTurYrED+5zT+Vcp6R2Vt6PJdubXlqZnzzHvyHTgxv8AKxv9LR+p1KjUxABJIH6lHkjufBV1VkSAo9c7L98cBPtb3cbAIjKhx1N7KsL0WmlAOa6lsV1osXvJBt5qAQSpmOIjK4R46QusGZ9AL+tkzkVUVt7LmzcFZO2FO/5YneeXurrYm5rwcc5FhmGDO/4j+gWdJLs1nbZm6WZ4dxyzt0Xvfwg2i6WhLXG4hkMbD/Rha8N8i4gdLLyXeuhDCHtbawIdYZEL2T4c7K+y7PhAzMzRO883StDgMuTcLfyrXA0+jHyJ9eGa5KQhRyooKpJBq6y4lBlxHTJAHPIHFCL1wYnFqAHMcuQmiy5ABmpyGXLmuQAOobwPFR6SXCcJ0PofBSpFCcL5cRp0PQoAtIyPVPc1VNNW2ydkRx4K3a8IAZhS3RLgpQxAAMK8Y+Okp+1UsY4wvd59pb9AvcMC8a+PdIRNRzWywTMJ6h0bgPRzvRLXQ0dnnFLLkb62uquaS5J5kqQ2YNcbjKx+gUB7hfLRYtFCoZI1WWxNgyzm+Etj4vI+jeak7rUYllGMXaOHNekMhFrAZDRJd+prjx+/JkGbHpYbBzXSv5XP/EK7p942wgD7G9rByZYeys6eOOG7yO87Mu4+A6Kun3ibI/s2Zk3AAGV7XtiNhey5L2O50T6LbkE/yYmnkRZWTFn6LN1+zAIOd7XBVxXvLInPaLkAmyypI1hsz29O1KfC6N1ySC3Ic8l7HunVxS0VO+E3j7FjW9MDQwtI4EFpB8F4Rs2pMmOVsIe/E0Z2JOPQNccgc7W4L6C2TRCCGOIADs2BpsLAut3j5m581Rgj1bJPKv2SJDouS5gKKEheqSM4X4pSExzkgcgBcKRPCa5qABkrkjylQBxCboitC5zUAMUd8Wd1JATXtQBEfSMObgrCCnGEC5NuqrJ5yDaydS19siUAXLYwNAlQopw4ZJ4cgAiwvxl2T2+znyD5qVwn/ILtkH9jifyhbgoFdSMlifE8XZKx0bhza9pa4ehXGdT0z5MZSunkLWWuGk+IGqsDujOGknDc6C+f+kuzIXUle6GbJ0b3wvOlyO6HDobAjoV6M0A3vxA8Lt4Keq0y7Hjmp2ee7vRuikDXNLSDY3XolO7JRNp07HYX2HAp1PLcKa3tlOOVK0WEtK14sRdQXbFja7tGsAfpjt3tLKfTyqSSCuqmjrlMqqWgw3JOqlADREkdbJVZqiNGEnjc2A/ykabNJakSXZ4aTbQ5jovW9k1JlhjkOr2NJ/FbvfW68oZWl5sW2tqttuXtUvZ2Jb/CaSHA6jFoR5rbx6arTJfMhOPaTVlyaSmgrlceYKuKbdJdADg5Ea66AUwuKADyxJEjJ+a5ADWvsigoN8krCUAECUtTcVk4vQAOeAEWIVXPAGnNXYIUWqiDtEARqOexVi16z7rtPFWNFU3yOqALTtAkxIBKTGgDxb477A7OeOtY3uz2ZIRwlYO6T+Jgt/4+qo90d5nn928YsIyN87civcd5tlx1lLLTyZCRuTvuPGbHjwcAfUL552DsyWCrljlZhdGSx3K4OrTxBGYPIhYZteuyrxqftpG2mr8Z+Wwt5pIH5oRYhxyWNionyeiXMJUyNyrIJVMbIuo42MmmsVV1W0Yxe7xfopVRRMkN3XNuqjy7PAGQHomWkdWn2Qaara5/cJN9eS9F+HMY/fE690epcT7Befx07sQtr7BaPY+0ZIDhjNybFwIBDrXtfiNToickze2Lmxu4ak9NewcElwq2grxMC5otY2IOoOvD3Uxua9BNNbR49S5emFKQlMLUll04OS4ErQlJQAPAuTXzDguQAcRjmly4J4jSEoAGUgKUkJhKAHlDkT0jmoAhVDL6hRY47HI2U+RQpggC4p3gjPVQdvV4giL7XNjhbzNtfAKN+1I2N/iNLgMgCCSeAyWYqpXOeXPNy7Un26BY5Mqno2x4vblmS2pt2WQOlmkdgF7Nvlfg1rdL3QKOEnvuFibZcuiz+9lRJHVCN4tHE5rmNGjmnPEeZ1HktdA4FocMwQCPArLyd6WuizxZSbb7FAUesg4jUKUGpzmrBI3plVFXYcirGGtB4qLNSgqDLRlvyusn9TN0aOGQc0R7xZZWlnlLsLbHrchWn2WcjVo8iUrS+jJ18FrqhzDiZhxHu2OhvorTZwLAGkgvfmSs3TU7o52vncXNFyAG5B3UBWUNa9z3uZE91wGsytYDUm/M+y45k0l19L5lSMVm3xa4tNOIPQreUNWJI2vH8wzHIjIj1uvNtmUrm5v18c8zc/Uk+a1W6tZcyR30s8efdd7D1WuCkq0iXyobn2fw0/aLsSCSmlytPOJLpANVHfITohhpKPG1ADGxrkdtlyAJmJRZzyRWm4TXhAAWgnVO7NKFRbQ3hzLYRfCSDIdLj7o4+J5cdUtWpW2NEOnpFtU1jIx33AchqT4AZqBLvDGPlje7rkB73WddJiJLiSTqSbldeyleen0Vz48rsl1W2ZnElpwDgLA/UjNV1TXSvye8npkB5gWunvKBIRxCVun2x1MrpBKVgzKLM26ixHO/AqYCkY5jd/8AY3axCZo78N8XMxnX019VW7pVeKLszqzT8J/wt3VTMY0l5Abp49LcVgKiH7LUNt/Dfm38DuHi2/sq8f8A6Y3D/wCCp6o0jURMDUuGw1UqWjZvYCdtlW1byRyHurSRqzO8+0hEyw+Y5NH6+AWkrb0jKnrljd39otFQ+/yizfC/+16DTgO0Xn25+xi2PtX5mbMg/d4etyfNbTY7yG4T/Ll5cF3ycSWmjnjZdtpkzsW30XTODRdSmNBUauiGElSfj+ljy/CG2V8rhHE0ue7QDlxJPADmVrdg0DaYEE4pH2xu4ZXs1v8ASLnx+gg7u11JDGMDX4ngdo4gEk8bm/yg3sAtK+IHPIjUdVbgiVz9PM8jJb4fQolBzXFAFPyyR4WkZFUkoQBOSAJ4YSgBGrkRsK5AAqOa48FJcbqLRQYSeqlO8EAVu35zFTvcDmQGg9XG1x4Ak+SxdPduY04harfIj7MLf/Yz2csfA8jqpM/NFmDidlg2xzCQoLOYyPJFxcwkSNWxpKHI2+mRRShuTJCNkUOOK19dL52K5la/TAMuOfskmH0N/wDKkRkevun0vqF2/jIM0JffGb8v9Dgs7vywdgwgWMbwPItIPlcBbCQZ+SzW+1LjpXkassT1sVrNbaES9WM2BWl8TS75gLHxHFWZesNuVORI6M3s8Ej8Qz9rrZGJw4KfLjc0+OCyLlrTfIOomWFjg+21gaM2NJv+BvzHzOXmFf71VvZwm3zSdwdL/MfT3CZ8NKOzZZCNS1g8ALn3HotcC1Lsyz9+psIoQAABYDQITjhl6OHoR/pTMKj17O5i4tII8tfpdF8yY4/1osICnVYu0qPRSXAUuQZKTZYuym2Y7NzeRur2k2o+LiXM4sv/AMeRVBAcM/4slZuHNdlvW0LkS3pm7pu+0ObmHC4KkNiKzm5e0DidC45EYmDqPmHmM7dCte1quivZbPOyT61oAIk9rUUpCE4g0LkoXIAa2K2YTZRkiteOaY6RvFAGY3yfan/8jfZyyzRkCFe7+zZxNGhxOI65AH6lZ+k0spMvNluHiCXFJfI5FELwFFdG5cJCNRdCk66JSC82XNkvomvPNMloVsE/UdckSnyy9EIusjt5rtCz2Occx4Kr3ji/cS8nRvB/tNlYSfMOqZVtBjeDoWu9iux8Cuzy/dqS1TF1db+7L9V6uxgA0zXm+7jA2VpvYhzeRvmFuquoIBN8gL+QVGeG2kc2kYbfinPb2uMLW3DRqMWZJ9B6LVbnUeClZlbGS+3icvoAsq9nbTF7gbuPtkAF6HTwhrGt+60D0C7llRCkanvkR/JBeL+GYT5Dw/7ZOc3JTtcCJ8kXZzrd37pI9Fa3VTHlIetj+n6KyaVI1yWp7RSV5s/ENWkK3Y4OFxoq6sZqpOyJLsLTq0/Q6IxvT0dyztJklsgje1+fdc1wtrkbr0mOoDgCNCLg8wdF5rI3jqVtN3TenZ0BaeOYPDoqcPbRFnXCZciQJcYQEtlQTBrpUEMXIAoWyG+qmxzXzVY9SIHoAo99c3x/hPuqFt9Vfb4DOI9Hj0w2/VUcRUl/7Zbj/wAIlwzXCIowZxCmQNLtEu9D6BmMLjHwRZBbJMBTTTYrSIssSLG/LVEeOajTRZZLTezNrQWUaeKZUHuOHNp9kyJ92+CJP8p8D7Jo7OMx9DTdnI1lrEAE9SM/RWu8M2CI/wBeQ89foCkwjtA8svc2xSOOPpZo7qgbfc58jWAHCwEk8Lnh9Pqrsk/sg7aGbs0wfKD93Oy2cxyvwCze60QbI5t8w0OI5BxIHsVoJzc25e6mzPdhQOMXzKK4JGtTyFiziIU7bPb1B+h/2pjCodWe83zUqMqa1+xZH+QFUzVQoHYXg8DkfNWVQFWVDNVi+Hs3S2tFpUNPBa3ce/YOaT8sht0BDT7krHUc+JgucxkfELXbkyNwytxDFiBw3zthAvbkrMT5R5+Zalo0TguBT0NxVJIPxLkB71yAKV0Z1C6AWOiMHDRcZB6IAo99r9lG4aB5B825exWbiddbqtp2VETonHCXDIng4aO9bLz9kbo5HRvycwkEXuMuIPEKbLPOyrDW50T43dVNp3WF1XWCmUullm1wbbCPzF08AJQ3JIzRCXAPsZIwHgoU0Vhdpt04KdJdR5IzZdTaOPkiUoydZSpTdp8D7KPE2xPVFL+7fp+i3nlmL4M9M67MZa7FHIxul25nO/Wyl08L3g44i0uIsb6X428wlhdLIxsTWDC54e4kW43uFa7drXw08khzc2NxBAt3rWb9SFbl/UeP6eSzbZmjq5JGyXIeWYswLMOEGwOYy6r1TZNSJYmSD+dt8tL8det15DWyY8JEbWWaG2bfMtGbnX4kr0zce/2OP83/ACKhVezbFtGgskenBBncgUgVT+8PFTYiqufUeKsIzksMq/Ypwv8AUNIoEzVOuosyxpFMMFs59nlp0dmPFWtFUdhMyUaNNnDm05FUdSDa41GYVnRTiVnXQhNjvTMs2PfJ6k2xAINwcweBB0KXAs3ubtAuYYXHvRfL1j/1p5haRegntHl0tPQhiXJ4K5dOGdmKfC267sCiNyQAssAtosdvRQD/AOS3I91r2887NeOugIW1fosvvW4iNrbfM72BNvWyW1tDw9Mz0Mh4qwodVSREtOE+XgreF+HPkpmudFW+NlggulNyB6qsrNtAHC0XPsq9xkkNy4+WS7xPYSqvo0d/vOUaeqjF7vaPMKlNCTqSfNN/ZYSPJJtOGmSxVMJ7sjT5qbE64VIdmM5I8EjoxYadc0R5Ep8hfi01wa3ZmBxvbQKv38h7Sm7KM4XPe3PTJpufrZO2LtmFoIkaQTbMaZKi373ojjkj7JhkwtJNrhoJI1PPJWPNN87J7ip40YT9kVuIMdHfEbAnCRfx1C9D3djwU8Q/p9ySsdTb3ymQdpCA1uZDQQRcWF7n+oLd0jLRxjL5G5DTQadFjKlPg4/ZrklqFO65U15s1QbJkKyBVZW8VPiOShVgufC59AjwPyCxzLk38d/qyWChShKClcFiyiSJKMlGoJMEgzsCbHzUyoVZNqUnT2adrRr6ao7ORkjdWnMDi05OHmF6Ax4IDgbggEHmCLheR7qwSTyCIPdm7M64WDNxv/3MherxwhoDW5NaAAOgFgF6GPrZ5Wbh6FfIuS4Ei0MQdSzjbJQnNU7HlpdCIHBAArZLO76i0UZAz7TXldp/75K/qJbaKr27HjgflcgYh+XP2BXK6GnswsrLi/EZqPtLanZRtcBiBNiL21GV1LZIAM1XbShbI17Af6gPqFhK3yUN64IlBLiOI6nMrQQALKbOJbkdQtDSTqbJvZdi16llhTHBK1y4lZ6NQLgmOYiPKHiSaG9gTogolRSg8FPJQ3I9TvsZyo2JGTfDa/JX7dsOFg5gsLDJI5iC+NNN1IlY4vtFg/bMbuY8kv2+L74VO6FCdTrafJf1GFeJL6ZauqoyT32/KeIXUkmSzlTs8FWOzJe6AdW5H/KasqsWcLx75L1jkYFV8b1MiSsdA6lVUru8VaVJR9093jVTlzx+5jIx/wBZ1DPDn08VxR7PSO1albZsdwdliGmEhb+8n73UM/kHgQMX5lpDdGazouLV6ErS0eTdezbAWK5GsuXRSvCFMwnjbwUhI5oQBWStsnsbceHojz0pdpa6DSxkOs4WQB5xvBCIpXsb8oII6BwDreAvbyUSKlDm4tHDQj/uYWn+I9BYxzNGThgd+Jty31F/7VS0rO6PJZvSWjadvkpayFwzLDfmM2n/AAi0E4Vs8XVPWbKffFEfyn9Cp7l09leLIpWmXUcgshy1AWdftCRmT2OHll6oX7UxcVz0NXlTNAakJvbhU7Kgc0Zk4XHJz3LEzJplUP7Su+0JXJ32JRlTe1UYzBJ2gS+oyskY0l0DtAk7ULnod/ISbKM+Ig3b/wCwkdVtHFANcOvjbL1TzDEvIiyinCsY6kW1VEGtdmfKyV0R4SnzAK09BFkJlbXAcf8Aa9C3Bnb9kGC+LE4yAixDzw8MOEX6Ly5vZt44nczmfLkvUvhtSkUpkcCDLISL/caA0H1Dk+Jaoy8itwamGoPEKUDdRkokVJCFIK5NxXSoAEYkN7FKCa5AFLVl7DcZgo7H4mgl1rcEauGSiMQAWrpI54zFIMTXeRB4Fp4ELzVhtdv3XEehsvSBqPJeZVX8R/43/wDIrLJ8N8X0NZc0JGFEauSNQxzFX11HGf5G352F1ZPUSpTMSWVzdlRngR4FAj2U43tJaxtmL/qreLRdBx8U8wmLV0vpTT7PkaLgh2bQbA5Bzg2/1CsIN253cQPG/stBO0CAkCxu3MZfzNV0nWGRHmswP7FdxfobGw5eaediZXxn0Cvan+I/8RSDQrNxO+hlkp/Sjj2G3i930T/2EzmT4k/orgaLlxyhvZ/0q27NYwXDRfwQhQ3Vs/RR0Jg0VU2zG8BbwNvZWe7W6MdU6RjpjG5oa5gtjxC5DjYkad31T3a+Sn7rG1ZDbiXjy7N6OGHs10XOzfhvTsAEsjn2vk0CMG50JuT6ELaxhrQGtAAaAABkABkABwCGUOM5+aZJISqb7CuuuFuKVyhzuPMropIdMFyr3rkAf//Z"
  name             : "Kenneth Beck."
  pronouns         : "he/him."  
  bio              : "High school graduate with lots of potential for anything and everything."
  location         : "United States."
  employer         : "Richland High School."
  uri              : "https://github.com/RMgametopspot/ReadME"
  email            : "Jkjbeck12@gail.com" 

  # Academic websites
  Resume?          : "https://github.com/RMgametopspot/ReadME/blob/main/Resume.pdf"
  3 Projects       : "https://github.com/RMgametopspot/ReadME/blob/main/Three%20Projects.pdf"
  Read me          : "https://github.com/RMgametopspot/ReadME/blob/main/README.md"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : # "https://orcid.org/yourorcidurl"
  semantic         : # URL
  ssrn             : # URL
  pubmed           : # "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL
  zotero           : # URL


  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "https://github.com/RMgametopspot/ReadME/blob/main/Resume.pdf"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  artstation       : # Username
  bluesky          : # "bsky.app" # Replace this with you Bluesky username
  facebook         : "RMgametopspot"
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : RMgametopspot
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # RMgametopspot
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/ for social media previews
breadcrumbs              : false # true, false (default)
words_per_minute         : 90
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Social media default site image
og_description           :  # Social media default site image description
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
